spring:
  application:
    name: eureka-client-payment-gateway

server:
  port: 9020

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    seviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
